services:
  # PostgreSQL Database
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'

  # Backend service (Spring Boot App)
  onlybuns-backend:
    build:
      context: ./onlybuns-be
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_OUTPUT_FILE: /logs/myapp.log
    depends_on:
      - postgres
    volumes:
      - ./logs:/logs

  # Frontend service (Vue.js App)
  onlybuns-frontend:
    build:
      context: ./onlybuns-fe
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - onlybuns-backend
    networks:
      - default

  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
