services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'

  onlybuns:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_OUTPUT_FILE: /logs/myapp.log  # Specify the log file path inside the container
    depends_on:
      - postgres
    volumes:
      - ./logs:/logs  # Mount local logs directory to /logs in the container

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'  # Exposing port 80 of pgAdmin to host port 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Default admin email
      PGADMIN_DEFAULT_PASSWORD: admin  # Default admin password
    depends_on:
      - postgres
